/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package home_package;

import javax.swing.JOptionPane;
import java.sql.*;

/**
 *
 * @author HP
 */
public class StartTest extends javax.swing.JFrame {

    private int counter;
    private int nq1;
    private String course1;
    private String ans;
    private String time1;
    private String pass;

    /**
     * Creates new form StartTest
     */
    public StartTest() {
        initComponents();
    }

    public StartTest(String para, int nq, String course,String time) {
        initComponents();
        setLocationRelativeTo(null);
        pass=para;
        nq1=nq;
        course1=course;
        time1=time;
        
        counter = 1;

        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/examinationsystem", "root", "");
            String sql = "Select Question,Qop1,Qop2,Qop3,Qop4 from questions where QID=?;";
            PreparedStatement pst = con.prepareStatement(sql);
            String coursest = course + counter;
            pst.setString(1, coursest);
            ResultSet rs = pst.executeQuery();
            if (rs.next()) {
                question.setText(rs.getString("Question"));
                op1.setText(rs.getString("Qop1"));
                op2.setText(rs.getString("Qop2"));
                op3.setText(rs.getString("Qop3"));
                op4.setText(rs.getString("Qop4"));
                op1.setActionCommand(rs.getString("Qop1"));
                op2.setActionCommand(rs.getString("Qop2"));
                op3.setActionCommand(rs.getString("Qop3"));
                op4.setActionCommand(rs.getString("Qop4"));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        question = new javax.swing.JLabel();
        op1 = new javax.swing.JRadioButton();
        op2 = new javax.swing.JRadioButton();
        op3 = new javax.swing.JRadioButton();
        op4 = new javax.swing.JRadioButton();
        next = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        question.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        question.setText("jLabel1");

        buttonGroup1.add(op1);
        op1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        op1.setText("jRadioButton1");

        buttonGroup1.add(op2);
        op2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        op2.setText("jRadioButton2");

        buttonGroup1.add(op3);
        op3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        op3.setText("jRadioButton3");

        buttonGroup1.add(op4);
        op4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        op4.setText("jRadioButton4");

        next.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        next.setText("Next");
        next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(question, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(op3, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(op1, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(45, 45, 45)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(op4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(op2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addComponent(next, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(question, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(106, 106, 106)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(op1)
                    .addComponent(op2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(op3)
                    .addComponent(op4))
                .addGap(18, 18, 18)
                .addComponent(next)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextActionPerformed
        
        ans = buttonGroup1.getSelection().getActionCommand();
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/examinationsystem", "root", "");
            String sql = "Insert into results values (?,?,?,?,?,1);";
            PreparedStatement pst = con.prepareStatement(sql);
            pst.setString(1,pass);
            pst.setString(2,course1+counter);
            pst.setString(3,time1);
            pst.setString(4,ans);
            pst.setString(5,course1);
            pst.executeUpdate();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        
        counter++;
        
        if (counter < nq1) {
            try {
                Class.forName("com.mysql.jdbc.Driver");
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/examinationsystem", "root", "");
                String sql = "Select Question,Qop1,Qop2,Qop3,Qop4 from questions where QID=?;";
                PreparedStatement pst = con.prepareStatement(sql);
                String coursest = course1 + counter;
                pst.setString(1, coursest);
                ResultSet rs = pst.executeQuery();
                if (rs.next()) {
                    question.setText(rs.getString("Question"));
                    op1.setText(rs.getString("Qop1"));
                    op2.setText(rs.getString("Qop2"));
                    op3.setText(rs.getString("Qop3"));
                    op4.setText(rs.getString("Qop4"));
                    op1.setActionCommand(rs.getString("Qop1"));
                    op2.setActionCommand(rs.getString("Qop2"));
                    op3.setActionCommand(rs.getString("Qop3"));
                    op4.setActionCommand(rs.getString("Qop4"));
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }
        else if(counter == nq1)
        {
            next.setText("Submit");
            
            try {
                Class.forName("com.mysql.jdbc.Driver");
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/examinationsystem", "root", "");
                String sql = "Select Question,Qop1,Qop2,Qop3,Qop4 from questions where QID=?;";
                PreparedStatement pst = con.prepareStatement(sql);
                String coursest = course1 + counter;
                pst.setString(1, coursest);
                ResultSet rs = pst.executeQuery();
                if (rs.next()) {
                    question.setText(rs.getString("Question"));
                    op1.setText(rs.getString("Qop1"));
                    op2.setText(rs.getString("Qop2"));
                    op3.setText(rs.getString("Qop3"));
                    op4.setText(rs.getString("Qop4"));
                    op1.setActionCommand(rs.getString("Qop1"));
                    op2.setActionCommand(rs.getString("Qop2"));
                    op3.setActionCommand(rs.getString("Qop3"));
                    op4.setActionCommand(rs.getString("Qop4"));
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }
        else if (counter > nq1){
            JOptionPane.showMessageDialog(null, "Congratulations! You completed the test");
            
            dispose();
            UserHome uh = new UserHome(pass);
            uh.setVisible(true);
        }
    }//GEN-LAST:event_nextActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StartTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StartTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StartTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StartTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StartTest().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton next;
    private javax.swing.JRadioButton op1;
    private javax.swing.JRadioButton op2;
    private javax.swing.JRadioButton op3;
    private javax.swing.JRadioButton op4;
    private javax.swing.JLabel question;
    // End of variables declaration//GEN-END:variables

}
